DROP TABLE IF EXISTS POSTS;
  
CREATE TABLE POSTS (
  id int AUTO_INCREMENT  PRIMARY KEY,
  title VARCHAR(250) NOT NULL,
  subtitle VARCHAR(250) NOT NULL,
  href VARCHAR(250) NOT NULL,
  updated DATETIME,
  content TEXT NOT NULL,
  banner VARCHAR(250) DEFAULT NULL
);
